name: riverpod
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.0-dev.11
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  image_picker: ^1.0.4
  firebase_storage: ^11.3.1
  provider: ^6.0.5
  uuid: ^4.1.0
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
