// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNzyuWTtuEz2OMrEKQSHAQ_y4bQiOfESo',
    appId: '1:158187019710:web:628bc30768ee2bc8f62def',
    messagingSenderId: '158187019710',
    projectId: 'insta-clone-flutter-da5c3',
    authDomain: 'insta-clone-flutter-da5c3.firebaseapp.com',
    storageBucket: 'insta-clone-flutter-da5c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7OCBMCWqBNpMdjVbiobf4Rbee87I79M',
    appId: '1:158187019710:android:7d72ba2f322397a1f62def',
    messagingSenderId: '158187019710',
    projectId: 'insta-clone-flutter-da5c3',
    storageBucket: 'insta-clone-flutter-da5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6MS2Q8ymoNalg7GolYiXtX1IxRXy5bg',
    appId: '1:158187019710:ios:248061a4b1ab962ef62def',
    messagingSenderId: '158187019710',
    projectId: 'insta-clone-flutter-da5c3',
    storageBucket: 'insta-clone-flutter-da5c3.appspot.com',
    iosBundleId: 'com.example.riverpod',
  );
}
